# permissions for end users to view deploymenttargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: deploymenttarget-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: application-api
    app.kubernetes.io/part-of: application-api
    app.kubernetes.io/managed-by: kustomize
  name: deploymenttarget-viewer-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - deploymenttargets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - deploymenttargets/status
  verbs:
  - get
